version: '3'

services:
  openthaigpt-0.1.0-beta:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "0"
    image: openthaigpt-0.1.0-beta
    shm_size: '64gb'
    command: generate.py --load_8bit --base_model $BASE_MODEL --lora_weights 'kobkrit/openthaigpt-0.1.0-beta'
    restart: unless-stopped
    volumes:
      - openthaigpt-0.1.0-beta:/root/.cache # Location downloaded weights will be stored
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  openthaigpt-0.1.0-beta:
    name: openthaigpt-0.1.0-beta
